### ISSUE TITLE
More dispersible models & account managers

### ISSUE THREAD

**Issue by whitmanc** [accelestate/accelestate#55]
The following models should have one of the following associations added to each of them:
1. Dispersible - model that can be "dispersed" among any number of beneficiaries
2. Has one relationship - model is associated with a single beneficiary via a drop down

* 4.1 4.11 - these are dispersible, should be labeled as "Beneficiaries"
  * ~~Bank Accounts~~
  * ~~Stocks~~
  * Life Insurance - add "estimated value" - Hold off on this one, going to be changed in next version.
  * ~~Social Security~~ Need to validate for estimated value
  * Insurances - Hold off on this one, going to be changed in next version.
  * ~~Real Property~~ Need to validate for estimated value
  * ~~Business Holdings~~
  * ~~Other Investments~~
  * ~~Personal Property~~
  * ~~Pension Survivorship Plans - add "estimated value"~~
  * ~~Military Benefits - add "estimated value"~~
  * ~~Foreign Holdings - treated like Stocks~~

* 6.1 - 6.13 - has_one relationship between model and beneficiary. These have a field labeled "Account Manager", which should be a drop down of beneficiaries to select from. Only one can be selected (has_one relationship to model)
  * ~~Social Media~~
  * ~~Professional Associations~~
  * ~~Email Accounts~~
  * ~~Club Memberships~~
  * ~~Airline Memberships~~
  * ~~Driver's License/Auto registration~~
  * ~~Firearm Registration: "Firearm to be registered to"~~
  * ~~Safe Deposit Boxes~~
  * ~~Passport~~

Model refs (or in web app): https://docs.google.com/document/d/1-NL7ZtxqPk4rCt4s2KQOHVvv_OiAaPDI3dKVVE8yDzg/edit

Updated 5/13

Related changes:
~~* Change wording of “Disbursements” to “Disbursements / Responsible Beneficiary” so that the default title will make sense out-of-the-box (then each model can change the title individually if necessary)~~

**Comment by dira** [comment]
@whitman 
For section 6 I see that the following have a beneficiary reference as well: `firearm registration`, `safe deposit boxes`, `passport`. Should I work on them too?

**Comment by dira** [comment]
@whitman regarding disbursable: for Bank Accounts, for example, having a share of the benefit means that, when showing a Bank Account, the value for that Beneficiary can be shown (if a beneficiary has 20% of an account that has $3000, they have $600).
For stocks, I displayed the number of shares.

What about Life insurance and Social security - they don't have an associated value, what should be displayed?

**Comment by dira** [comment]
@whitman Some of the models in the issue description are debts (`Recurring Bills`, `Mortgages`, `Bank Loans`, `Other Debts`). Are they disbursable? Also labeled 'beneficiaries'? (they are not disbursable in the document, as far as I see)

**Comment by whitmanc** [comment]
I called the client to clarify some of these questions.

> @whitman Some of the models in the issue description are debts (Recurring Bills, Mortgages, Bank Loans, Other Debts). Are they disbursable? Also labeled 'beneficiaries'? (they are not disbursable in the document, as far as I see)


These (Recurring Bills, Mortgages, Bank Loans, Other Debts) are no longer dispersible, nor do they have a beneficiary, according to client. Thank you for bringing it up


> What about Life insurance and Social security- they don't have an associated value, what should be displayed?
What about the models shown in section 4 in the issue request - Other Investments, Pension Survivorship Plans, Military Benefits, Foreign Holdings - that don't have a 'value' or 'estimated value'?


These models (Life Insurance, Social Security, Survivorship Plans, Military Benefits) should have an "estimated value" field added to them. I was told foreign holdings should be treated like stocks.


> For section 6 I see (in the doc) that the following have a beneficiary reference as well: firearm registration, safe deposit boxes, passport. Should I work on them too?

I've looked in the latest spec, they should be as follows:
* Firearm Registration: "Firearm to be registered to" with single drop down to select a beneficiary
* Safe Deposit Boxes: "Account Manager" single drop down to select a beneficiary
* Passport: "Account Manager" single drop down to select a beneficiary

**Comment by dira** [comment]
@whitman thank you!
Not sure what model 'Insurances' (in the disbursables' section) stands for.
And another question: should `estimated_value` be a string (as the other estimated value fields added by Eaven) or a float?

**Comment by whitmanc** [comment]
I am going to work against this issue today, push the code & update the issue accordingly. Seems pretty clear how to make a model dispersible, the mixins look great. 

@dira `estimated_value` should definitely be a numerical data type such as a float. Past fields that should be numerical fields, not strings, i've opened an issue for [here](https://github.com/accelestate/accelestate/issues/58)

**Comment by whitmanc** [comment]
@dira 
I ended up getting stuck working on my first model (:(), and I haven't been able to figure it out yet. On the Social Security model, everything is setup how it is in with stocks in and I can create a new record for social securities with beneficiaries, but I can't view them. For some reason, the model isn't getting passed into the `DependsOnBeneficiaries` (see [here](https://github.com/accelestate/accelestate/commit/b8e3098b7f569a9f609a26aae93ce23c4103dc09#diff-746d06c959b5ef2464b58f6a068d7c62R5) to see where I am referring to)

Would it be possible to help look into why this isn't working? I am guessing I am missing something, but no matter how much I look I can't find any discrepancies between your commit for stocks and my commit for social securities (other than that I added a field: `estimated_value`).

Your commit for making stocks dispersible: 4726dbc54ce89ab89cd81abfa14a285847be082a
My commit for making social securities dispersible: b8e3098b7f569a9f609a26aae93ce23c4103dc09

Please let me know what you think.

**Comment by dira** [comment]
@whitman 
Pushed the <mighty> fix :)

**Comment by whitmanc** [comment]
@dira Woohoo! Thx. I will take it from here.
